config/routes.rb
Msdoc::Application.routes.draw do
  match "inputs/new" => "inputs#new"
  match "inputs/create" => "inputs#create"
  match "inputs/show/:id" => "inputs#show"

  root :to => 'inputs#new'

end

app/models/input.rb
class Input < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController

  require 'rest-client'
  require 'date'
  require 'json'
  
  def new
    @input = Input.new
  end

  def create
    @input = Input.new
    if @input.save
      @render_url = "https://dws.docmosis.com/services/rs/render"
      @access_key = "access key" #enter your access key here

      @template = "GENEX_PAS_TEMPLATE.odt"
      # The output file name
      @output="#{Rails.root}/public/GENEX_PAS_#{@input.id}.doc";


      RestClient.proxy = ENV['http_proxy'];

      RestClient.post(@render_url,
        {
          'accessKey' => @access_key,
          'templateName' => @template,
          'outputName' => @output,
          'data' => {
            'date' => Date.today,
            'display_claimant_name' => @input.display_claimant_name,
            'jurisdictional_state' => @input.jurisdictional_state,
            'claim_number' => @input.claim_number,
            'call_log.talked_to' => @input.talked_to,
            'call_log.call_datetime' => @input.call_datetime,
            'call_log.call_notes' => @input.call_notes,
            'diagnosis' => @input.diagnosis,
            'referral_document.document_date_mdy' => @input.document_date_mdy,
            'referral_document.name' => @input.name,
            'referral_document.suffix' => @input.suffix,
            'referral_document.description' => @input.ref_doc_description,
            'additional_question.description' => @input.add_que_description,
            'additional_question.response' => @input.response,
            'additional_question.opinion' => @input.opinion,
            'ur_recommendation_name' => @input.recommendation_name,
            'clinical_summary' => @input.clinical_summary,
            'rationale' => @input.rationale,
            'cited_guidelines' => @input.cited_guidelines,
            'reviewer_display_name' => @input.reviewer_display_name,
            'reviewer_specialty_name' => @input.reviewer_specialty_name,
            'reviewer_license_description' => @input.reviewer_license_description
          }
        }.to_json, :content_type => :json) {|response, request, result, &block|
        case response.code
        when 200
          File.open(@output,"w"){|f|f.syswrite(response.to_s)}
        else
          puts "Error response:\n\n#{response.code} #{response}\n\n"
          response.return!(request, result, &block)
        end
      }
    end
    redirect_to inputs_new_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/views/inputs/new.html.haml
%h2
  = "Add the Data to Create The .doc File"

= form_for @input, :url => inputs_create_path(@input) do |f|
  %p
    = f.label :display_claimant_name
    = f.text_field :display_claimant_name

  %p
    = f.label :jurisdictional_state
    = f.text_field :jurisdictional_state

  %p
    = f.label :claim_number
    = f.text_field :claim_number

  %p
    = f.label :talked_to
    = f.text_field :talked_to

  %p
    = f.label :call_datetime
    = f.text_field :call_datetime

  %p
    = f.label :call_notes
    = f.text_area :call_notes, :rows => '3', :cols => '40'

  %p
    = f.label :diagnosis
    = f.text_field :diagnosis

  %p
    = f.label :document_date_mdy
    = f.text_field :document_date_mdy

  %p
    = f.label :name
    = f.text_field :name

  %p
    = f.label :suffix
    = f.text_field :suffix

  %p
    = f.label :ref_doc_description
    = f.text_area :ref_doc_description, :rows => '3', :cols => '40'

  %p
    = f.label :add_que_description
    = f.text_area :add_que_description, :rows => '3', :cols => '40'

  %p
    = f.label :response
    = f.text_area :response, :rows => '3', :cols => '40'

  %p
    = f.label :opinion
    = f.text_area :opinion, :rows => '3', :cols => '40'

  %p
    = f.label :recommendation_name
    = f.text_field :recommendation_name

  %p
    = f.label :clinical_summary
    = f.text_area :clinical_summary, :rows => '3', :cols => '40'

  %p
    = f.label :rationale
    = f.text_area :rationale, :rows => '3', :cols => '40'

  %p
    = f.label :cited_guidelines
    = f.text_area :cited_guidelines, :rows => '3', :cols => '40'

  %p
    = f.label :reviewer_display_name
    = f.text_field :reviewer_display_name

  %p
    = f.label :reviewer_specialty_name
    = f.text_field :reviewer_specialty_name

  %p
    = f.label :reviewer_license_description
    = f.text_field :reviewer_license_description

  %p
    = f.submit "Create .doc File"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Msdoc</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>